name: CI
on:
  pull_request:
    paths:
      - .github/workflows/ci.yaml
      - .sbtopts
      - build.sbt
      - .scalafmt.conf
      - project/**
      - src/**

defaults:
  run:
    shell: bash

env:
  GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}

jobs:
  code-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: sbt headerCheckAll
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: sbt test
