name: publish
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGES }}

jobs:
  publish:
    runs-on: self-hosted
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.9.9_2.12.19
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: git log
    - run: git tag
    #- run: sbt clean publish
